# Generated by Django 5.1.4 on 2025-10-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='hid',
            new_name='venue_id',
        ),
    ]
